package admin

const indexHTML = `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>dsmctl Gateway</title><style>
body{font:15px system-ui,sans-serif;max-width:1180px;margin:2rem auto;padding:0 1rem;color:#172033;background:#f6f8fb}
h1{margin-bottom:.25rem}.card{background:white;border:1px solid #dce2ea;border-radius:10px;padding:1rem;margin:1rem 0;overflow:auto}
input,select,button{font:inherit;padding:.5rem;margin:.2rem;border:1px solid #aeb8c5;border-radius:6px}button{cursor:pointer;background:#1d6fe8;color:white}.danger{background:#b42318}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.6rem;border-bottom:1px solid #e4e8ee;vertical-align:top}code{overflow-wrap:anywhere}
#message{white-space:pre-wrap;color:#b42318}.muted{color:#627084;font-size:.9rem}.secret{background:#fff7d6;border:1px solid #e2b93b;padding:.8rem;white-space:pre-wrap}</style></head><body>
<h1>dsmctl Gateway</h1><p class="muted">同一個 gateway 可動態管理最多 32 台 NAS。管理 token 只保存在目前分頁的 sessionStorage；MCP bearer token 只在建立或輪替時顯示一次。</p>
<div class="card"><h2>管理員登入</h2><input id="token" size="48" placeholder="Admin token"><button onclick="saveToken()">使用 token</button><br>
<input id="bootstrap" size="48" placeholder="首次啟用 bootstrap token"><button onclick="bootstrapAdmin()">首次啟用</button><div id="message"></div></div>
<div class="card"><h2>新增 NAS</h2><input id="name" placeholder="名稱"><input id="url" size="32" placeholder="https://nas:5001"><input id="username" placeholder="DSM 帳號">
<select id="tls"><option value="system_ca">System CA</option><option value="pinned_fingerprint">Pinned fingerprint</option></select><input id="fingerprint" size="40" placeholder="SHA-256 fingerprint"><button onclick="addProfile()">新增</button></div>
<div class="card"><h2>NAS 清單</h2><button onclick="loadProfiles()">重新整理</button><table><thead><tr><th>名稱</th><th>URL</th><th>版本</th><th>憑證</th><th>動作</th></tr></thead><tbody id="profiles"></tbody></table></div>
<div class="card"><h2>MCP token</h2><p class="muted">scope 彼此獨立；新 token 預設只有 nas.read。NAS allowlist 必須明確列出，不能使用萬用字元。</p>
<input id="tokenName" placeholder="token 名稱"><input id="tokenNAS" size="28" placeholder="NAS 名稱，以逗號分隔">
<label><input type="checkbox" class="scope" value="nas.read" checked>read</label><label><input type="checkbox" class="scope" value="nas.plan">plan</label><label><input type="checkbox" class="scope" value="nas.apply">apply</label><label><input type="checkbox" class="scope" value="nas.admin">admin</label>
<button onclick="createMCPToken()">建立 token</button><div id="issued" class="secret" hidden></div>
<table><thead><tr><th>名稱 / ID</th><th>scope</th><th>NAS allowlist</th><th>狀態</th><th>動作</th></tr></thead><tbody id="tokens"></tbody></table></div>
<div class="card"><h2>高風險 apply 核准</h2><p class="muted">核准必須在這個管理頁建立，不接受 MCP header 或對話內的核准。預設 10 分鐘、綁定 plan hash、NAS revision 與 requesting token，使用一次即失效。</p>
<input id="approvalHash" size="48" placeholder="plan SHA-256 hash"><input id="approvalNAS" placeholder="NAS"><input id="approvalRevision" type="number" min="1" placeholder="profile revision"><input id="approvalToken" size="34" placeholder="requesting token ID"><button onclick="createApproval()">建立核准</button>
<table><thead><tr><th>plan / NAS</th><th>requesting token</th><th>期限</th><th>狀態</th></tr></thead><tbody id="approvals"></tbody></table></div>
<div class="card"><h2>稽核紀錄</h2><button onclick="loadAudit()">重新整理</button><button onclick="exportAudit()">下載 JSONL</button><pre id="audit"></pre></div>
<script>
const $=id=>document.getElementById(id);$('token').value=sessionStorage.getItem('dsmctlAdminToken')||'';
function show(e){$('message').textContent=e instanceof Error?e.message:String(e||'')}
function saveToken(){sessionStorage.setItem('dsmctlAdminToken',$('token').value.trim());refreshAll()}
async function api(path,options={}){options.headers=Object.assign({'Content-Type':'application/json','Authorization':'Bearer '+(sessionStorage.getItem('dsmctlAdminToken')||'')},options.headers||{});let r=await fetch('/admin/api'+path,options),t=await r.text(),v;try{v=JSON.parse(t)}catch{v={error:t}}if(!r.ok)throw new Error(v.error||r.statusText);return v}
async function bootstrapAdmin(){try{let r=await fetch('/admin/api/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:$('bootstrap').value})}),v=await r.json();if(!r.ok)throw new Error(v.error);$('token').value=v.admin_token;$('bootstrap').value='';saveToken()}catch(e){show(e)}}
async function addProfile(){try{let pinned=$('tls').value==='pinned_fingerprint',fp=$('fingerprint').value.trim(),confirmed=!pinned||confirm('請確認這是由另一個可信管道取得的 SHA-256 certificate fingerprint：\n'+fp);if(!confirmed)return;await api('/profiles',{method:'POST',body:JSON.stringify({name:$('name').value,url:$('url').value,username:$('username').value,tls_mode:$('tls').value,certificate_fingerprint:fp,confirm_certificate_fingerprint:confirmed})});loadProfiles()}catch(e){show(e)}}
function cell(row,text){let td=row.insertCell();td.textContent=text;return td}function button(parent,label,fn,danger=false){let b=document.createElement('button');b.textContent=label;b.onclick=fn;if(danger)b.className='danger';parent.appendChild(b)}
async function loadProfiles(){try{let v=await api('/profiles'),body=$('profiles');body.textContent='';for(const p of v.profiles){let row=body.insertRow();cell(row,(p.default?'★ ':'')+p.name);cell(row,p.url);cell(row,String(p.revision));cell(row,p.session_stored?'web session':p.password_stored?'password':'尚未設定');let actions=cell(row,'');button(actions,'預設',()=>setDefault(p.name));button(actions,'測試',()=>testNAS(p.name));button(actions,'Web login',()=>webLogin(p.name));button(actions,'密碼/OTP',()=>passwordLogin(p.name));button(actions,'刪除',()=>removeNAS(p),true)}show('')}catch(e){show(e)}}
async function setDefault(n){try{await api('/profiles/'+encodeURIComponent(n)+'/default',{method:'POST',body:'{}'});loadProfiles()}catch(e){show(e)}}async function testNAS(n){try{show(JSON.stringify(await api('/profiles/'+encodeURIComponent(n)+'/test',{method:'POST',body:'{}'}),null,2))}catch(e){show(e)}}
async function passwordLogin(n){let password=prompt('DSM password（只用於驗證與加密保存）');if(password===null)return;let otp=prompt('OTP（不需要可留空）')||'';try{await api('/profiles/'+encodeURIComponent(n)+'/credentials/password',{method:'POST',body:JSON.stringify({password,otp})});password=otp='';loadProfiles()}catch(e){password=otp='';show(e)}}
async function webLogin(n){try{let s=await api('/profiles/'+encodeURIComponent(n)+'/weblogin/start',{method:'POST',body:'{}'}),popup=window.open(s.login_url,'dsmctl_signin','width=560,height=720');let listener=async e=>{if(e.origin!==s.nas_origin)return;let d=e.data||{};if(!d.code)return;window.removeEventListener('message',listener);try{await api('/profiles/'+encodeURIComponent(n)+'/weblogin/complete',{method:'POST',body:JSON.stringify({enrollment_id:s.enrollment_id,code:d.code,rs:d.rs,state:d.state||s.state})});if(popup)popup.close();loadProfiles()}catch(x){show(x)}};window.addEventListener('message',listener)}catch(e){show(e)}}
async function removeNAS(p){if(!confirm('刪除 '+p.name+' 及其 credentials？'))return;try{await api('/profiles/'+encodeURIComponent(p.name)+'?revision='+p.revision,{method:'DELETE'});loadProfiles()}catch(e){show(e)}}
async function createMCPToken(){try{let scopes=[...document.querySelectorAll('.scope:checked')].map(x=>x.value),nas=$('tokenNAS').value.split(',').map(x=>x.trim()).filter(Boolean),v=await api('/mcp-tokens',{method:'POST',body:JSON.stringify({name:$('tokenName').value,scopes,nas_allowlist:nas})});$('issued').hidden=false;$('issued').textContent='請立即保存，離開後無法再次取得：\n'+v.bearer_token;loadTokens()}catch(e){show(e)}}
async function loadTokens(){try{let v=await api('/mcp-tokens'),body=$('tokens');body.textContent='';for(const t of v.tokens){let row=body.insertRow();cell(row,t.name+'\n'+t.id);cell(row,t.scopes.join(', '));cell(row,t.nas_allowlist.join(', '));cell(row,t.revoked_at?'revoked':t.expires_at?'expires '+t.expires_at:'active');let actions=cell(row,'');button(actions,'輪替',()=>rotateToken(t.id));button(actions,'撤銷',()=>revokeToken(t.id),true)}}catch(e){show(e)}}
async function rotateToken(id){if(!confirm('舊 token 將立即失效，確定輪替？'))return;try{let v=await api('/mcp-tokens/'+id+'/rotate',{method:'POST',body:'{}'});$('issued').hidden=false;$('issued').textContent='請立即保存新的 token：\n'+v.bearer_token;loadTokens()}catch(e){show(e)}}async function revokeToken(id){if(!confirm('確定撤銷？'))return;try{await api('/mcp-tokens/'+id,{method:'DELETE'});loadTokens()}catch(e){show(e)}}
async function createApproval(){try{await api('/approvals',{method:'POST',body:JSON.stringify({plan_hash:$('approvalHash').value,nas:$('approvalNAS').value,profile_revision:Number($('approvalRevision').value),requesting_token_id:$('approvalToken').value})});loadApprovals()}catch(e){show(e)}}async function loadApprovals(){try{let v=await api('/approvals?include_consumed=true'),body=$('approvals');body.textContent='';for(const a of v.approvals){let row=body.insertRow();cell(row,a.plan_hash+'\n'+a.nas+' @ '+a.profile_revision);cell(row,a.requesting_token_id);cell(row,a.expires_at);cell(row,a.consumed_at?'consumed '+a.consumed_at:new Date(a.expires_at)<new Date()?'expired':'ready')}}catch(e){show(e)}}
async function loadAudit(){try{$('audit').textContent=JSON.stringify((await api('/audit?limit=100')).events,null,2)}catch(e){show(e)}}async function exportAudit(){try{let r=await fetch('/admin/api/audit/export?limit=1000',{headers:{'Authorization':'Bearer '+(sessionStorage.getItem('dsmctlAdminToken')||'')}});if(!r.ok)throw new Error('匯出失敗');let u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download='dsmctl-audit.jsonl';a.click();URL.revokeObjectURL(u)}catch(e){show(e)}}async function refreshAll(){await Promise.allSettled([loadProfiles(),loadTokens(),loadApprovals(),loadAudit()])}if($('token').value)refreshAll();
</script></body></html>`
