package application

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http/cookiejar"
	"net/url"
	"strings"
	"time"

	"github.com/ychiu1211/dsmctl/internal/config"
	"github.com/ychiu1211/dsmctl/internal/credentials"
	"github.com/ychiu1211/dsmctl/internal/provision"
	"github.com/ychiu1211/dsmctl/internal/runtime"
	"github.com/ychiu1211/dsmctl/internal/tlstrust"
)

// Provisioner is the DSM setup-window protocol used to bring up a fresh NAS. It
// is the seam the application operation is tested against; the default
// implementation forwards to the sessionless internal/provision core, and both
// the CLI and (later) the gateway/MCP adapters reuse this one operation rather
// than re-implementing the sequence.
type Provisioner interface {
	EstablishSetupSession(ctx context.Context, target provision.Target) error
	CreateFirstAdmin(ctx context.Context, target provision.Target, req provision.AdminRequest) error
	DisableBuiltinAdmin(ctx context.Context, target provision.Target, scramble string) error
	Login(ctx context.Context, target provision.Target, username, password string) error
	CompleteSetup(ctx context.Context, target provision.Target, opts provision.SetupOptions) error
	Harden(ctx context.Context, target provision.Target, req provision.AdminRequest) error
}

type directProvisioner struct{}

func (directProvisioner) EstablishSetupSession(ctx context.Context, target provision.Target) error {
	return provision.EstablishSetupSession(ctx, target)
}

func (directProvisioner) CreateFirstAdmin(ctx context.Context, target provision.Target, req provision.AdminRequest) error {
	return provision.CreateFirstAdmin(ctx, target, req)
}

func (directProvisioner) DisableBuiltinAdmin(ctx context.Context, target provision.Target, scramble string) error {
	return provision.DisableBuiltinAdmin(ctx, target, scramble)
}

func (directProvisioner) Login(ctx context.Context, target provision.Target, username, password string) error {
	return provision.Login(ctx, target, username, password)
}

func (directProvisioner) CompleteSetup(ctx context.Context, target provision.Target, opts provision.SetupOptions) error {
	return provision.CompleteSetup(ctx, target, opts)
}

func (directProvisioner) Harden(ctx context.Context, target provision.Target, req provision.AdminRequest) error {
	return provision.Harden(ctx, target, req)
}

// WithProvisioner overrides the DSM provisioning protocol implementation, for
// tests that must exercise the operation without a live NAS.
func WithProvisioner(provisioner Provisioner) ServiceOption {
	return func(service *Service) {
		if provisioner != nil {
			service.provisioner = provisioner
		}
	}
}

// WithProvisionSink installs the deployment's credential sink so ProvisionNAS
// (used by the gateway/MCP adapter) can persist a provisioned password without
// the adapter passing a sink per call. The CLI passes its keyring sink directly
// to ProvisionFirstAdmin instead and does not need this.
func WithProvisionSink(sink ProvisionSink) ServiceOption {
	return func(service *Service) {
		if sink != nil {
			service.provisionSink = sink
		}
	}
}

// ProvisionRequest describes a first-administrator provisioning run. The
// administrator username is the operator's choice; the password is generated by
// the operation and never carried here or in the result.
type ProvisionRequest struct {
	Name           string `json:"nas" jsonschema:"NAS profile name to record for the provisioned device"`
	URL            string `json:"url" jsonschema:"DSM https URL of the NAS in its first-run setup window"`
	AdminUser      string `json:"admin_user" jsonschema:"Administrator username to create (operator's choice, never generated)"`
	DeviceName     string `json:"device_name,omitempty" jsonschema:"Optional DSM server name (hostname) to set"`
	AutoUpdate     string `json:"auto_update,omitempty" jsonschema:"DSM update policy: security (default), all, or notify"`
	Analytics      bool   `json:"analytics,omitempty" jsonschema:"Opt in to Synology device analytics / Active Insight (default off)"`
	PasswordLength int    `json:"password_length,omitempty" jsonschema:"Generated administrator password length (default 24, minimum 16)"`
}

// ProvisionResult reports a provisioning outcome. It deliberately carries no
// password: the generated credential goes only to the sink, and is retrieved
// afterward exclusively through the human-gated reveal.
type ProvisionResult struct {
	NAS                  string   `json:"nas" jsonschema:"NAS profile name recorded for the provisioned device"`
	AdminUser            string   `json:"admin_user" jsonschema:"Administrator account created"`
	URL                  string   `json:"url" jsonschema:"DSM URL provisioned"`
	AdministratorCreated bool     `json:"administrator_created" jsonschema:"The first administrator was created and its login verified"`
	PasswordStored       bool     `json:"password_stored" jsonschema:"The generated password was persisted to the credential store"`
	WizardFinished       bool     `json:"wizard_finished" jsonschema:"The post-account setup wizard steps completed"`
	BuiltinAdminDisabled bool     `json:"builtin_admin_disabled" jsonschema:"The built-in admin account was scrambled and expired in the setup session"`
	Hardened             bool     `json:"hardened" jsonschema:"Post-setup hardening (auto-block, telemetry agent, device name) completed"`
	Warnings             []string `json:"warnings,omitempty" jsonschema:"Non-fatal problems; the administrator is created and usable"`
}

// ProvisionPersist is the deployment-specific persistence the operation hands to
// its sink after the administrator is created and verified. The CLI stores the
// password in the OS keyring and records the profile in config.json; the gateway
// stores it in the encrypted vault bound to a new NAS profile. The operation
// itself never writes either store, so the same operation serves every surface.
type ProvisionPersist struct {
	Name     string
	URL      string
	Username string
	Password string
}

// ProvisionSink persists a freshly provisioned administrator credential and its
// profile. It is the only place the generated password leaves the operation, so
// no adapter (and no MCP result) ever receives the plaintext.
type ProvisionSink interface {
	PersistProvisioned(ctx context.Context, persist ProvisionPersist) error
}

// ProvisionProfileSpec describes a NAS profile to create for an un-enrolled
// (discovered) device before its administrator is provisioned. TLS trust is the
// certificate observed on first contact (trust-on-first-use).
type ProvisionProfileSpec struct {
	Name                   string
	URL                    string
	TLSMode                string
	CertificateFingerprint string
}

// ProvisionProfileCreator is implemented by sinks that can create a NAS profile
// for a not-yet-enrolled device (the gateway vault, the CLI config). Only sinks
// that implement it support ProvisionDiscoveredNAS.
type ProvisionProfileCreator interface {
	CreateProvisionProfile(ctx context.Context, spec ProvisionProfileSpec) error
}

// ProvisionFirstAdmin is the single provisioning operation shared by the CLI and
// (via WI-086) the gateway/MCP adapters. It generates the administrator
// password, drives the DSM setup-window sequence through the Provisioner, hands
// the password to the sink to persist, and finishes the wizard. The password is
// stored the moment the account is verified — before the best-effort wizard and
// hardening steps — so an interrupted run leaves a usable, recoverable
// administrator. The caller owns the target's HTTP client (cookie jar + TLS
// policy for the NAS's fresh certificate).
func (s *Service) ProvisionFirstAdmin(ctx context.Context, target provision.Target, req ProvisionRequest, sink ProvisionSink) (ProvisionResult, error) {
	if err := config.ValidateName(req.Name); err != nil {
		return ProvisionResult{}, err
	}
	req.AdminUser = strings.TrimSpace(req.AdminUser)
	if req.AdminUser == "" {
		return ProvisionResult{}, errors.New("provision requires an administrator username")
	}
	if !strings.HasPrefix(strings.ToLower(strings.TrimSpace(target.BaseURL)), "https://") {
		return ProvisionResult{}, fmt.Errorf("provision requires an https target so the administrator password is not sent in cleartext, got %q", target.BaseURL)
	}
	if sink == nil {
		return ProvisionResult{}, errors.New("provision requires a credential sink")
	}
	length := req.PasswordLength
	if length == 0 {
		length = credentials.DefaultGeneratedPasswordLength
	}

	// Start the setup session (log in as the built-in admin, empty-password
	// during first-run) so the account-creation compound is authorized like the
	// browser wizard.
	if err := s.provisioner.EstablishSetupSession(ctx, target); err != nil {
		return ProvisionResult{}, fmt.Errorf("could not start the DSM setup session; is the NAS in its first-run setup window? %w", err)
	}

	password, err := credentials.GeneratePassword(length)
	if err != nil {
		return ProvisionResult{}, err
	}
	scramble, err := credentials.GeneratePassword(length)
	if err != nil {
		return ProvisionResult{}, err
	}
	adminReq := provision.AdminRequest{Username: req.AdminUser, Password: password, DeviceName: req.DeviceName, ShareLocation: req.Analytics}

	result := ProvisionResult{NAS: req.Name, AdminUser: req.AdminUser, URL: target.BaseURL}
	if err := s.provisioner.CreateFirstAdmin(ctx, target, adminReq); err != nil {
		return result, fmt.Errorf("no administrator was created (you can retry): %w", err)
	}
	// Disable the built-in admin while the setup (admin) session is still held —
	// DSM only lets the reserved admin be modified by itself, so this must happen
	// before logging in as the new administrator. It is best-effort so a quirk
	// cannot fail an otherwise-good provision, but it is what stops DSM's first-run
	// welcome wizard from reappearing, so a failure is surfaced as a warning.
	if err := s.provisioner.DisableBuiltinAdmin(ctx, target, scramble); err != nil {
		result.Warnings = append(result.Warnings, "built-in admin not disabled (DSM may keep showing the welcome wizard): "+err.Error())
	} else {
		result.BuiltinAdminDisabled = true
	}
	if err := s.provisioner.Login(ctx, target, req.AdminUser, password); err != nil {
		return result, fmt.Errorf("administrator %q was created but the verification login failed: %w", req.AdminUser, err)
	}
	result.AdministratorCreated = true

	// Persist the only copy of the password before the best-effort steps can
	// fail. On failure the account exists but is unrecoverable, so this is fatal.
	if err := sink.PersistProvisioned(ctx, ProvisionPersist{Name: req.Name, URL: target.BaseURL, Username: req.AdminUser, Password: password}); err != nil {
		return result, fmt.Errorf("administrator created, but persisting its credential failed; rotate it: %w", err)
	}
	result.PasswordStored = true

	if err := s.provisioner.CompleteSetup(ctx, target, provision.SetupOptions{AutoUpdate: req.AutoUpdate, Analytics: req.Analytics}); err != nil {
		result.Warnings = append(result.Warnings, "setup wizard not fully finished: "+err.Error())
	} else {
		result.WizardFinished = true
	}
	if err := s.provisioner.Harden(ctx, target, adminReq); err != nil {
		result.Warnings = append(result.Warnings, "post-setup hardening incomplete: "+err.Error())
	} else {
		result.Hardened = true
	}
	return result, nil
}

// ProvisionNAS is the deployment-agnostic entry point used by the gateway and
// the remote MCP tool: it provisions an already-added, credential-less NAS
// profile using the sink installed with WithProvisionSink. The profile must
// already exist with its TLS trust decided; a profile that already holds a
// stored password is refused so a provisioning grant cannot re-provision or
// hijack a set-up NAS. The generated password never appears in the result.
func (s *Service) ProvisionNAS(ctx context.Context, req ProvisionRequest) (ProvisionResult, error) {
	if s.provisionSink == nil {
		return ProvisionResult{}, errors.New("provisioning is not configured on this server")
	}
	if err := config.ValidateName(req.Name); err != nil {
		return ProvisionResult{}, err
	}
	cfg, err := s.configSnapshot(ctx)
	if err != nil {
		return ProvisionResult{}, err
	}
	profile, ok := cfg.NAS[req.Name]
	if !ok {
		return ProvisionResult{}, fmt.Errorf("NAS profile %q is not configured; add it before provisioning", req.Name)
	}
	if s.credentialStore != nil {
		if stored, err := s.credentialStore.HasPassword(ctx, req.Name); err == nil && stored {
			return ProvisionResult{}, fmt.Errorf("NAS %q already has a stored administrator credential; provisioning is only for a fresh, credential-less profile", req.Name)
		}
	}
	target, err := provisionHTTPTarget(profile)
	if err != nil {
		return ProvisionResult{}, err
	}
	req.URL = profile.URL
	return s.ProvisionFirstAdmin(ctx, target, req, s.provisionSink)
}

// ProvisionDiscoveredNAS provisions a NAS that has no profile yet: it validates
// the target is an https, LAN-reachable (private/loopback/link-local) address,
// trusts the certificate it observes on first contact (TOFU), creates a pinned
// profile through the sink, and then provisions the first administrator exactly
// like an enrolled profile. It is the fully-remote path (a discovered device is
// outside every allowlist), so it is gated by the nas.provision scope at the
// transport, restricted to LAN addresses here, and never adds the new profile
// to any token's allowlist. The generated password never appears in the result.
func (s *Service) ProvisionDiscoveredNAS(ctx context.Context, req ProvisionRequest) (ProvisionResult, error) {
	if s.provisionSink == nil {
		return ProvisionResult{}, errors.New("provisioning is not configured on this server")
	}
	creator, ok := s.provisionSink.(ProvisionProfileCreator)
	if !ok {
		return ProvisionResult{}, errors.New("this server cannot create a profile for an un-enrolled device")
	}
	targetURL := strings.TrimSpace(req.URL)
	if targetURL == "" {
		return ProvisionResult{}, errors.New("provisioning a discovered device requires its https url")
	}
	host, err := validateLANProvisionURL(ctx, targetURL)
	if err != nil {
		return ProvisionResult{}, err
	}
	name := strings.TrimSpace(req.Name)
	if name == "" {
		name = deriveProvisionProfileName(host)
	}
	if err := config.ValidateName(name); err != nil {
		return ProvisionResult{}, fmt.Errorf("provisioned profile name %q is invalid: %w", name, err)
	}
	cfg, err := s.configSnapshot(ctx)
	if err != nil {
		return ProvisionResult{}, err
	}
	if _, exists := cfg.NAS[name]; exists {
		return ProvisionResult{}, fmt.Errorf("a profile named %q already exists; provision it by name instead of as a discovered device", name)
	}
	// Trust the certificate observed on first contact. A factory-fresh device is
	// self-signed and there is no human to confirm a fingerprint, so provisioning
	// pins exactly what it sees; a later administrator can re-pin. Restricting the
	// target to LAN addresses bounds where a generated password can be sent.
	observed, err := tlstrust.Observe(ctx, targetURL)
	if err != nil {
		return ProvisionResult{}, fmt.Errorf("cannot observe the TLS certificate of %s: %w", targetURL, err)
	}
	spec := ProvisionProfileSpec{Name: name, URL: targetURL, TLSMode: "pinned_fingerprint", CertificateFingerprint: observed.Fingerprint}
	if err := creator.CreateProvisionProfile(ctx, spec); err != nil {
		return ProvisionResult{}, fmt.Errorf("create profile for the discovered device: %w", err)
	}
	target, err := provisionHTTPTarget(config.Profile{URL: targetURL, TLSMode: spec.TLSMode, CertificateFingerprint: spec.CertificateFingerprint})
	if err != nil {
		return ProvisionResult{}, err
	}
	req.Name = name
	req.URL = targetURL
	return s.ProvisionFirstAdmin(ctx, target, req, s.provisionSink)
}

// validateLANProvisionURL requires an https URL whose host is a
// private/loopback/link-local address, so an un-enrolled provisioning request
// (which sends a generated password to a device nobody has vetted) cannot be
// pointed at an arbitrary public host.
func validateLANProvisionURL(ctx context.Context, rawURL string) (string, error) {
	return validateLANURL(ctx, rawURL, true)
}

// validateLANURL requires a URL whose host is a private/loopback/link-local
// address (a hostname is resolved and every resolved address must be LAN-scoped).
// requireHTTPS enforces https for password-carrying flows; install traffic
// carries no password so it may use the assistant's http endpoint.
func validateLANURL(ctx context.Context, rawURL string, requireHTTPS bool) (string, error) {
	parsed, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil || parsed.Host == "" {
		return "", fmt.Errorf("url %q is not a valid URL", rawURL)
	}
	if requireHTTPS && !strings.EqualFold(parsed.Scheme, "https") {
		return "", errors.New("provisioning a discovered device requires an https url so the administrator password is not sent in cleartext")
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return "", errors.New("url must be http or https")
	}
	host := parsed.Hostname()
	if host == "" {
		return "", errors.New("provision url has no host")
	}
	addresses := []net.IP{}
	if ip := net.ParseIP(host); ip != nil {
		addresses = append(addresses, ip)
	} else {
		resolved, err := net.DefaultResolver.LookupIP(ctx, "ip", host)
		if err != nil || len(resolved) == 0 {
			return "", fmt.Errorf("cannot resolve provision host %q: %w", host, err)
		}
		addresses = resolved
	}
	for _, ip := range addresses {
		if !ipIsLANScoped(ip) {
			return "", fmt.Errorf("remote provisioning is restricted to LAN/VPN addresses; %s is not private/loopback/link-local", ip)
		}
	}
	return host, nil
}

func ipIsLANScoped(ip net.IP) bool {
	return ip.IsLoopback() || ip.IsPrivate() || ip.IsLinkLocalUnicast()
}

// deriveProvisionProfileName turns a target host into a config-safe profile name
// when the caller does not supply one.
func deriveProvisionProfileName(host string) string {
	sanitized := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_', r == '.':
			return r
		default:
			return '-'
		}
	}, host)
	sanitized = strings.Trim(sanitized, "-_.")
	if sanitized == "" {
		return "provisioned-nas"
	}
	return "nas-" + sanitized
}

// provisionHTTPTarget builds a provisioning HTTP client that reuses the
// profile's stored TLS policy (the pinned fresh-NAS certificate) and adds a
// cookie jar to carry the DSM setup/login session across the compound calls.
func provisionHTTPTarget(profile config.Profile) (provision.Target, error) {
	jar, err := cookiejar.New(nil)
	if err != nil {
		return provision.Target{}, err
	}
	client := runtime.HTTPClient(profile)
	client.Jar = jar
	client.Timeout = 90 * time.Second
	return provision.Target{BaseURL: profile.URL, HTTPClient: client}, nil
}

// FinishSetup runs only the post-account wizard steps against a NAS whose
// administrator already exists, logging in with the supplied (already-stored)
// password. It completes a provisioning run that was interrupted after account
// creation. The password is an input the local adapter resolves from the
// credential store; it is never returned.
func (s *Service) FinishSetup(ctx context.Context, target provision.Target, username, password string, opts provision.SetupOptions) error {
	if strings.TrimSpace(username) == "" || password == "" {
		return errors.New("finishing setup requires the administrator account and its stored password")
	}
	if err := s.provisioner.Login(ctx, target, username, password); err != nil {
		return fmt.Errorf("log in as %q to finish setup: %w", username, err)
	}
	return s.provisioner.CompleteSetup(ctx, target, opts)
}

// DisableBuiltinAdmin retrofits a NAS whose built-in admin was left enabled
// because a provisioning run disabled it as the new administrator and DSM
// rejected that with error 105. It re-enters the setup (admin) session — which
// still works while the built-in admin is enabled with its empty setup password
// — and scrambles + expires the built-in admin the way the DSM wizard does. That
// also flips DSM's server-side admin_configured flag, so the first-run welcome
// wizard stops being presented on login. A NAS whose built-in admin is already
// disabled cannot start the setup session and returns that error.
func (s *Service) DisableBuiltinAdmin(ctx context.Context, target provision.Target) error {
	if !strings.HasPrefix(strings.ToLower(strings.TrimSpace(target.BaseURL)), "https://") {
		return fmt.Errorf("disabling the built-in admin requires an https target, got %q", target.BaseURL)
	}
	if err := s.provisioner.EstablishSetupSession(ctx, target); err != nil {
		return fmt.Errorf("could not start the DSM setup session; the built-in admin may already be disabled: %w", err)
	}
	scramble, err := credentials.GeneratePassword(credentials.DefaultGeneratedPasswordLength)
	if err != nil {
		return err
	}
	return s.provisioner.DisableBuiltinAdmin(ctx, target, scramble)
}
